baseURL = 'https://aminskey.github.io/'
languageCode = 'en-us'
title = "Amin's Page"
theme = 'ananke'
sectionPagesMenu = "main"
ignoreLogs = ['warning-goldmark-raw-html']

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[pagination]
    pagerSize = 3

[params]
    description = "A webpage showcasing my awesome projects"
    commentoEnable = true
    mainSections = ["posts"]
    author = "Syed M. Amin"
    custom_css = ["css/style.css"]

