baseURL = 'https://aminskey.github.io/'
languageCode = 'en-us'
title = "Amin's Portfolio"
theme = 'ananke'
sectionPagesMenu = "main"

[pagination]
    pagerSize = 3

[params]
    description = "A webpage showcasing my awesome projects"
    commenttoEnable = true
    mainSections = ["posts"]
    author = "Syed M. Amin"

